[package]
name = "embedded-flight"
version = "0.2.0"
description = "Embedded flight library"
edition = "2021"
license = "MIT"
repository = "https://github.com/matthunz/embedded-flight"

[workspace]
members = [
    "core",
    "control",
    "motors",
    "scheduler"
]

[dependencies]
embedded-flight-core = "0.1.0"
embedded-flight-control = "0.2.0"
embedded-flight-motors = "0.1.1"
embedded-time = "0.12.1"
nalgebra = "0.31.0"
