[package]
name = "embedded-flight"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "core",
    "control",
    "motors"
]

[dependencies]
embedded-flight-control = { path = "./control" }
embedded-flight-motors = { path = "./motors" }
nalgebra = "0.31.0"
