[package]
name = "embedded-flight"
version = "0.1.1"
description = "Embedded flight library"
edition = "2021"
license = "MIT"

[workspace]
members = [
    "control",
    "motors"
]

[dependencies]
embedded-flight-control = "0.1.0"
embedded-flight-motors = "0.1.0"
embedded-time = "0.12.1"
nalgebra = "0.31.0"
