[package]
name = "embedded-flight-scheduler"
version = "0.1.0"
edition = "2021"
description = "Embedded flight real-time scheduler library"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-time = "0.12.1"
